all:
	python3 example.py
	python3 -m pytest -v .

clean:
	rm -rf fmm_wrap.pyx
	rm -rf fmm_decl.pxd
	rm -rf fmm_wrap.pyxbld
	rm -rf fmm.c
	rm -rf fmm.h
	rm -rf *~
	rm -rf __pycache__
	rm -rf
	rm -rf *.pyc