[project]
name = "fmmgen"
version = "0.2.0"
description = "Tool for generating functions to generate Cartesian multipole expansions and fast multipole and Barnes-Hut codes that use these"
authors = [{ name = "Ryan Pepper", email = "ryan.pepper@onyxinsight.com" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.23.4,<3",
    "sympy>=1.11.1,<2",
    "Cython>=0.29.32",
]

[dependency-groups]
dev = [
    "pytest>=7.2.0,<10",
    "black>=22.10.0,<23",
    "flake8>=7.0,<8",
    "setuptools>=68",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 120
target-version = ['py312']
