all:
	python3 -m pytest .

clean:
	find . -name "*.cpp" -delete
	find . -name "*.h" -delete
	find . -name "*.c" -delete
	find . -name "*.pyx" -delete
	find . -name "*.pyxbld" -delete
	find . -name "*.pxd" -delete
