import sympy as sp
from .expansions import M, M_shift, L, L_shift, phi_deriv, Phi_derivatives
from .harmonic import (
    expand_local_subs,
    lift_multipole_subs,
    pivot_step,
    project_multipole,
    restrict_local,
)
from .utils import generate_mappings, Nterms
import logging

logger = logging.getLogger(name="fmmgen")


def generate_M_operators(order, symbols, M_dict):
    """
    generate_M_operators(order, symbols, index_dict):

    Generates multipole operators up to order.

    Input:
    order, int:
        Maximum order of multipole expansion

    symbols, list:
        List of sympy symbol type objects which
        define coordinate labels.

    index_dict:
        Forward mapping dictionary between
        monomials of symbols and array indices,
        generated by generate_mappings or otherwise.

    Output:
    list:
        List of symbolic multipole moments up to order.

    Example:
    >>> order = 2
    >>> x, y, z = sp.symbols('x y z')
    >>> map, _ = generate_mappings(order, [x, y, z])
    >>> generate_M_operators(order, (x, y, z), map)
    [q, -q*x, -q*y, -q*z, q*x**2/2, q*x*y, q*x*z, q*y**2/2, q*y*z, q*z**2/2]
    """
    x, y, z = symbols
    M_operators = []
    for n in M_dict.keys():
        M_operators.append(M(n, symbols))
    return M_operators


def generate_S2M_operators(order, symbols, M_dict, source_order=0):
    """Source-to-multipole: the multipole of one point source about a centre.

    Replaces the previous arrangement, in which the driver seeded a scratch
    multipole array with the source's raw moments and then called the general
    M2M to shift it to the cell centre. That worked only because a point
    source's multipole coefficients ARE its moments in this basis -- an
    undocumented basis assumption living in the driver rather than the
    operators -- and it paid for a full M2M when almost every input coefficient
    is known to be zero.

    A source of order s has a multipole supported only on the |n| = s shell, so
    this specialises M_shift to that sparse input:

        S2M_n = sum_{k : |n-k| = s} S[n-k] (x, y, z)^k / k!

    Sign convention follows M2M, i.e. (x, y, z) = centre - source, which is what
    the driver already passes. Note the old P2M used the opposite convention.
    """
    shell = [n for n in M_dict if sum(n) == source_order]
    source_size = len(shell)
    M = sp.MatrixSymbol("M", Nterms(order), 1)
    S = sp.MatrixSymbol("S", source_size, 1)

    subs = {M[M_dict[n]]: 0 for n in M_dict}
    for n in shell:
        # the |n| = s shell occupies the first source_size slots of M_dict, so
        # its index doubles as the index into the caller's S array
        subs[M[M_dict[n]]] = S[M_dict[n]]

    return [M_shift(n, order, symbols, M_dict, source_order=source_order).subs(subs)
            for n in M_dict]


def generate_M_shift_operators(order, symbols, M_dict, source_order=0):
    """
    generate_M_shift_operators(order, symbols, index_dict):

    Generates multipole shifting operators up to order.

    Input:
    order, int:
        Maximum order of multipole expansion

    symbols, list:
        List of sympy symbol type objects which define coordinate labels.

    index_dict:
        Forward mapping dictionary between
        monomials of symbols and array indices, generated by generate_mappings
         or otherwise.

    Output:
    list:
        List of symbolic multipole shifting operators up to order.

    Example:
    >>> order = 1
    >>> x, y, z = sp.symbols('x y z')
    >>> map, _ = generate_mappings(order, [x, y, z])
    >>> generate_M_shift_operators(order, (x, y, z), map)
    [M[0, 0], x*M[0, 0] + M[1, 0], y*M[0, 0] + M[2, 0], z*M[0, 0] + M[3, 0]]
    """
    x, y, z = symbols
    M_operators = []
    for n in M_dict.keys():
        M_operators.append(M_shift(n, order, symbols, M_dict, source_order=source_order))
    return M_operators


def generate_derivs(order, symbols, M_dict, source_order=0, harmonic_derivs=False):
    D = sp.MatrixSymbol("D", Nterms(order), 1)
    derivs = []
    for n in M_dict.keys():
        step = pivot_step(n) if harmonic_derivs else None
        if step is not None:
            k1, k2 = step
            derivs.append(-D[M_dict[k1]] - D[M_dict[k2]])
        else:
            derivs.append(Phi_derivatives(n, symbols))
    return derivs


def generate_L_operators(order, symbols, M_dict, L_dict, source_order=0):
    """
    generate_L_operators(order, symbols, index_dict):

    Generates local expansion operators up to given order.

    Input:
    order, int:
        Maximum order of multipole expansion

    symbols, list:
        List of sympy symbol type objects which define coordinate labels.

    index_dict:
        Forward mapping dictionary between
        monomials of symbols and array indices, generated by generate_mappings
        or otherwise.

    inline_derivs: bool
        Calculate derivatives inline rather than precalculating these.

    Output:
    list:
        List of symbolic local expansion operators up to order.

    Example:
    >>> order = 1
    >>> x, y, z = sp.symbols('x y z')
    >>> map, _ = generate_mappings(order, (x, y, z))
    >>> generate_L_operators(order, (x, y, z), map)
    [M[0, 0]/R - 1.0*x*M[1, 0]/R**3 - 1.0*y*M[2, 0]/R**3 - 1.0*z*M[3, 0]/R**3,
    -1.0*x*M[0, 0]/R**3, -1.0*y*M[0, 0]/R**3, -1.0*z*M[0, 0]/R**3]
    """
    x, y, z = symbols
    L_operators = []
    for n in L_dict.keys():
        L_operators.append(L(n, order, symbols, M_dict, source_order=source_order, eval_derivs=False))

    return L_operators


def generate_L_shift_operators(order, symbols, L_dict, source_order=0):
    """
    generate_L_shift_operators(order, symbols, index_dict):

    Generates multiple operators up to order.

    Input:
    order, int:
        Maximum order of multipole expansion

    symbols, list:
        List of sympy symbol type objects which
        define coordinate labels.

    index_dict:
        Forward mapping dictionary between
        monomials of symbols and array indices,
        generated by generate_mappings or otherwise.

    Output:
    list:
        List of symbolic local expansion shifting operators up to order.

    Example:
    >>> order = 1
    >>> x, y, z = sp.symbols('x y z')
    >>> map, _ = generate_mappings(order, (x, y, z))
    >>> generate_L_shift_operators(order, (x, y, z), map)
    [x*L[1, 0] + y*L[2, 0] + z*L[3, 0] + L[0, 0], L[1, 0], L[2, 0], L[3, 0]]
    """
    x, y, z = symbols
    L_shift_operators = []
    for n in L_dict.keys():
        L_shift_operators.append(L_shift(n, order, symbols, L_dict, source_order=source_order))
    return L_shift_operators


def generate_M2P_operators(
    order,
    symbols,
    M_dict,
    potential=True,
    field=True,
    source_order=0,
    harmonic_derivs=False,
):
    """
    generate_M2L_operators(order, symbols, index_dict)

    Generates potential and field calculation operators for the
    Barnes-Hut method up to order.
    """
    x, y, z = symbols
    R = sp.sqrt(x**2 + y**2 + z**2)

    terms = []

    # Phi_derivatives returns expressions in the atomic symbol Rinv, so the radial
    # dependence must be restored in terms of x, y, z before differentiating -
    # otherwise sp.diff treats Rinv as a constant and the field is wrong.
    V = L((0, 0, 0), order, symbols, M_dict, source_order=source_order, eval_derivs=True).subs(sp.Symbol("Rinv"), 1 / R)
    if potential:
        terms.append(V.subs(1 / R, "Rinv"))

    if field:
        Fx = -sp.diff(V, x).subs(1 / R, "Rinv")
        Fy = -sp.diff(V, y).subs(1 / R, "Rinv")
        Fz = -sp.diff(V, z).subs(1 / R, "Rinv")
        terms.append(Fx)
        terms.append(Fy)
        terms.append(Fz)

    return terms


def generate_L2P_operators(order, symbols, L_dict, potential=True, field=True):
    """
    generate_L2P_operators(order, symbols, index_dict):

    Generates potential and field calculation operators for the Fast
    Multipole Method up to order.

    Input:
    order, int:
        Maximum order of multipole expansion

    symbols, list:
        List of sympy symbol type objects which define coordinate labels.

    index_dict:
        Forward mapping dictionary between monomials of symbols and array
        indices, generated by generate_mappings or otherwise.

    Output:
    list:
        List of symbolic field calculation operators from local expansions up to
        order.

    Example:
    >>> order = 1
    >>> x, y, z = sp.symbols('x y z')
    >>> map, _ = generate_mappings(order, (x, y, z))
    >>> generate_L2P_operators(order, (x, y, z), map)
    [x*L[1, 0] + y*L[2, 0] + z*L[3, 0] + L[0, 0], -L[1, 0], -L[2, 0], -L[3, 0]]
    """
    x, y, z = symbols

    terms = []

    if potential:
        V = phi_deriv(order, symbols, L_dict, deriv=(0, 0, 0))
        terms.append(V)

    if field:
        Fx = -phi_deriv(order, symbols, L_dict, deriv=(1, 0, 0))
        Fy = -phi_deriv(order, symbols, L_dict, deriv=(0, 1, 0))
        Fz = -phi_deriv(order, symbols, L_dict, deriv=(0, 0, 1))
        terms.append(Fx)
        terms.append(Fy)
        terms.append(Fz)
    return terms


def generate_P2P_operators(symbols, M_dict, potential=True, field=True, source_order=0):
    order = source_order
    M_dict, _ = generate_mappings(source_order, symbols, "grevlex", source_order=source_order)
    x, y, z = sp.symbols("x y z")
    R = sp.sqrt(x**2 + y**2 + z**2)

    S_map, _ = generate_mappings(source_order, [x, y, z], key="grevlex", source_order=source_order)
    # print('S_map = {}'.format(S_map))

    M = sp.MatrixSymbol("M", Nterms(order), 1)
    S = sp.MatrixSymbol("S", Nterms(order), 1)

    subsdict = {M[i]: 0 for i in range(Nterms(order))}

    for key in S_map.keys():
        subsdict[M[M_dict[key]]] = S[M_dict[key]]

    # As in generate_M2P_operators: restore the radial dependence in terms of
    # x, y, z before differentiating, since Phi_derivatives emits atomic Rinv.
    V = L((0, 0, 0), order, symbols, M_dict, source_order=source_order).subs(sp.Symbol("Rinv"), 1 / R).subs(subsdict)

    terms = []
    # Note: R must be substituted late for correct derivatives!
    if potential:
        terms.append(V.subs(1 / R, "Rinv"))

    if field:
        Fx = -sp.diff(V, x).subs(1 / R, "Rinv")
        Fy = -sp.diff(V, y).subs(1 / R, "Rinv")
        Fz = -sp.diff(V, z).subs(1 / R, "Rinv")
        terms.append(Fx)
        terms.append(Fy)
        terms.append(Fz)
    return terms


# --------------------------------------------------------------------------
# Compressed (harmonic / trace-free) operator variants
#
# Each is the uncompressed operator with the transformations of
# fmmgen.harmonic applied to its input and output arrays. Nothing is
# rederived; the operators are linear in their expansion arrays, so
# substitution and projection suffice, and correctness follows from the
# identity H = Dec H[keep,keep] Dec^T verified in tests/test_harmonic.py.
#
# source_order > 0 is not supported: M_dict and L_dict are then built at
# different orders and the retained index set no longer lines up with both.
# The uncompressed path is unaffected.
# --------------------------------------------------------------------------

def _reject_source_order(source_order):
    if source_order:
        raise NotImplementedError(
            "compressed operators are implemented for source_order = 0 only; "
            f"got {source_order}. Use compress=False for higher source orders."
        )


def generate_S2M_operators_compressed(order, symbols, M_dict, keep_dict, source_order=0):
    _reject_source_order(source_order)
    ops = generate_S2M_operators(order, symbols, M_dict, source_order=source_order)
    return project_multipole(ops, order, symbols, M_dict, keep_dict)


def generate_M_shift_operators_compressed(order, symbols, M_dict, keep_dict, source_order=0):
    _reject_source_order(source_order)
    ops = generate_M_shift_operators(order, symbols, M_dict, source_order=source_order)
    subs = lift_multipole_subs("M", order, M_dict, keep_dict)
    ops = [expr.subs(subs) for expr in ops]
    return project_multipole(ops, order, symbols, M_dict, keep_dict)


def generate_L_operators_compressed(order, symbols, M_dict, L_dict, keep_dict, source_order=0):
    _reject_source_order(source_order)
    ops = generate_L_operators(order, symbols, M_dict, L_dict, source_order=source_order)
    subs = lift_multipole_subs("M", order, M_dict, keep_dict)
    ops = [expr.subs(subs) for expr in ops]
    return restrict_local(ops, L_dict, keep_dict)


def generate_L_shift_operators_compressed(order, symbols, L_dict, keep_dict, source_order=0):
    _reject_source_order(source_order)
    ops = generate_L_shift_operators(order, symbols, L_dict, source_order=source_order)
    subs = expand_local_subs("L", order, symbols, L_dict, keep_dict)
    ops = [expr.subs(subs) for expr in ops]
    return restrict_local(ops, L_dict, keep_dict)


def generate_L2P_operators_compressed(order, symbols, L_dict, keep_dict, potential=True, field=True):
    ops = generate_L2P_operators(order, symbols, L_dict, potential=potential, field=field)
    subs = expand_local_subs("L", order, symbols, L_dict, keep_dict)
    return [expr.subs(subs) for expr in ops]


def generate_M2P_operators_compressed(
    order, symbols, M_dict, keep_dict, potential=True, field=True,
    source_order=0, harmonic_derivs=False,
):
    _reject_source_order(source_order)
    ops = generate_M2P_operators(
        order, symbols, M_dict, potential=potential, field=field,
        source_order=source_order, harmonic_derivs=harmonic_derivs,
    )
    subs = lift_multipole_subs("M", order, M_dict, keep_dict)
    return [expr.subs(subs) for expr in ops]


def generate_M2L_compressed(order, symbols, M_dict, L_dict, keep_dict,
                            source_order=0, harmonic_derivs=False):
    """
    Compressed M2L, returning (derivs, L_operators) with a compact D array.

    The compressed contraction only ever references derivatives D_{i+j} with
    i, j retained, hence with third index <= 2, which is O(p^2) of the
    O(p^3) entries the uncompressed operator needs. Emitting the full
    derivative array would hand back a good part of the saving, so the used
    entries are collected and reindexed into a dense array.

    Ordering is inherited from the uncompressed index map, which is what makes
    harmonic_derivs still valid here: pivot_step targets have the same total
    degree and a lower z index, so under grevlex on [z, y, x] they keep an
    earlier slot than the entry that depends on them. Where a target falls
    outside the used set the derivative is computed directly instead.
    """
    _reject_source_order(source_order)

    L_ops = generate_L_operators_compressed(
        order, symbols, M_dict, L_dict, keep_dict, source_order=source_order
    )

    D_full = sp.MatrixSymbol("D", Nterms(order), 1)
    used = sorted(
        {
            a.i
            for expr in L_ops
            for a in expr.atoms(sp.matrices.expressions.matexpr.MatrixElement)
            if a.parent.name == "D"
        }
    )
    remap = {old: new for new, old in enumerate(used)}
    D = sp.MatrixSymbol("D", len(used), 1)
    L_ops = [expr.subs({D_full[o]: D[n] for o, n in remap.items()}) for expr in L_ops]

    rmap = {idx: n for n, idx in M_dict.items()}
    derivs = []
    for old in used:
        n = rmap[old]
        step = pivot_step(n) if harmonic_derivs else None
        if step is not None and all(M_dict[k] in remap for k in step):
            k1, k2 = step
            derivs.append(-D[remap[M_dict[k1]]] - D[remap[M_dict[k2]]])
        else:
            derivs.append(Phi_derivatives(n, symbols))

    return derivs, L_ops
